name: sound_mile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+13
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  shimmer: ^3.0.0
  flutter_screenutil: ^5.9.3
  path_provider: ^2.1.4
  just_audio: ^0.9.37
  fluttertoast: ^8.2.5
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.3
  audio_service: ^0.18.15
  just_audio_background: ^0.0.1-beta.13
  device_info_plus: ^11.3.3
  on_audio_query:
      path: ./on_audio_query/packages/on_audio_query
  palette_generator: ^0.3.3+6
  share_plus: ^11.0.0
  audio_session: ^0.1.25
  permission_handler: ^12.0.0+1
  flutter_media_delete: ^1.0.1
  android_intent_plus: ^6.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/mile.png


